// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pizza_Mia.Models;

#nullable disable

namespace Pizza_Mia.Migrations
{
    [DbContext(typeof(PizzaAppContext))]
    [Migration("20250523194120_AddUsersTable")]
    partial class AddUsersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pizza_Mia.Models.CategoriesDish", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("categories_dishes_pkey");

                    b.ToTable("categories_dishes", (string)null);
                });

            modelBuilder.Entity("Pizza_Mia.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("customers_pkey");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Pizza_Mia.Models.Delivery", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("DeliveryDate")
                        .HasColumnType("date")
                        .HasColumnName("delivery_date");

                    b.Property<int?>("IdIngredient")
                        .HasColumnType("integer")
                        .HasColumnName("id_ingredient");

                    b.Property<int?>("IdSupplier")
                        .HasColumnType("integer")
                        .HasColumnName("id_supplier");

                    b.Property<decimal?>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("deliveries_pkey");

                    b.HasIndex("IdIngredient");

                    b.HasIndex("IdSupplier");

                    b.ToTable("deliveries", (string)null);
                });

            modelBuilder.Entity("Pizza_Mia.Models.Dish", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("IdCategory")
                        .HasColumnType("integer")
                        .HasColumnName("id_category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("photo");

                    b.Property<decimal?>("Price")
                        .HasColumnType("money")
                        .HasColumnName("price");

                    b.Property<int>("СookingTime")
                        .HasColumnType("integer")
                        .HasColumnName("сooking_time");

                    b.HasKey("Id")
                        .HasName("dishes_pkey");

                    b.HasIndex("IdCategory");

                    b.ToTable("dishes", (string)null);
                });

            modelBuilder.Entity("Pizza_Mia.Models.DishIgredient", b =>
                {
                    b.Property<int>("IdDish")
                        .HasColumnType("integer")
                        .HasColumnName("id_dish");

                    b.Property<int>("IdIngredient")
                        .HasColumnType("integer")
                        .HasColumnName("id_ingredient");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.HasKey("IdDish", "IdIngredient")
                        .HasName("dish_igredients_pkey");

                    b.HasIndex("IdIngredient");

                    b.ToTable("dish_igredients", (string)null);
                });

            modelBuilder.Entity("Pizza_Mia.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("stock_quantity");

                    b.Property<int>("Unit")
                        .HasColumnType("integer")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("ingredients_pkey");

                    b.ToTable("ingredients", (string)null);
                });

            modelBuilder.Entity("Pizza_Mia.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int?>("IdCustomer")
                        .HasColumnType("integer")
                        .HasColumnName("id_customer");

                    b.Property<DateOnly?>("OrderDate")
                        .HasColumnType("date")
                        .HasColumnName("order_date");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<decimal?>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_amount");

                    b.HasKey("Id")
                        .HasName("orders_pkey");

                    b.HasIndex("IdCustomer");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Pizza_Mia.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_person");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("suppliers_pkey");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("Pizza_Mia.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Pizza_Mia.Models.Delivery", b =>
                {
                    b.HasOne("Pizza_Mia.Models.Ingredient", "Ingredient")
                        .WithMany("Deliveries")
                        .HasForeignKey("IdIngredient")
                        .HasConstraintName("deliveries_id_ingredient_fkey");

                    b.HasOne("Pizza_Mia.Models.Supplier", "Supplier")
                        .WithMany("Deliveries")
                        .HasForeignKey("IdSupplier")
                        .HasConstraintName("deliveries_id_supplier_fkey");

                    b.Navigation("Ingredient");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Pizza_Mia.Models.Dish", b =>
                {
                    b.HasOne("Pizza_Mia.Models.CategoriesDish", "CategoriesDish")
                        .WithMany("Dishes")
                        .HasForeignKey("IdCategory")
                        .HasConstraintName("fk_categories_dishes");

                    b.Navigation("CategoriesDish");
                });

            modelBuilder.Entity("Pizza_Mia.Models.DishIgredient", b =>
                {
                    b.HasOne("Pizza_Mia.Models.Dish", "Dish")
                        .WithMany("DishIgredients")
                        .HasForeignKey("IdDish")
                        .IsRequired()
                        .HasConstraintName("dish_igredients_id_dish_fkey");

                    b.HasOne("Pizza_Mia.Models.Ingredient", "Ingredient")
                        .WithMany("DishIgredients")
                        .HasForeignKey("IdIngredient")
                        .IsRequired()
                        .HasConstraintName("dish_igredients_id_ingredient_fkey");

                    b.Navigation("Dish");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("Pizza_Mia.Models.Order", b =>
                {
                    b.HasOne("Pizza_Mia.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("IdCustomer")
                        .HasConstraintName("orders_id_customer_fkey");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Pizza_Mia.Models.CategoriesDish", b =>
                {
                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("Pizza_Mia.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Pizza_Mia.Models.Dish", b =>
                {
                    b.Navigation("DishIgredients");
                });

            modelBuilder.Entity("Pizza_Mia.Models.Ingredient", b =>
                {
                    b.Navigation("Deliveries");

                    b.Navigation("DishIgredients");
                });

            modelBuilder.Entity("Pizza_Mia.Models.Supplier", b =>
                {
                    b.Navigation("Deliveries");
                });
#pragma warning restore 612, 618
        }
    }
}
